name: timer_stop_watch
description: Flutter Dart Package Try a timer and a stopwatch that can be modified freely.
version: 0.0.3
homepage: https://github.com/koreaksh/Timer_Stopwatch.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


