name: timer_stop_watch
description: Flutter Dart Package Try a timer and a stopwatch that can be modified freely.
version: 0.0.2
homepage: https://github.com/koreaksh/Timer_Stopwatch.git

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


